/* Mondelez Demo Hub · demo registry */
window.HUB_DEMOS = [
  { id:"converge", group:"Snapshot", name:"All channels → Joy Club", page:"mdlz-hub/converge/index.html", w:1280, h:832,
    steps:["All channels → Joy Club"] },
  { id:"snapshot", group:"Snapshot", name:"What this demo covers", page:"mdlz-hub/snapshot/index.html", w:1280, h:832,
    steps:["Acquire","Value exchange","Data · Live analytics","Data · Data visualisation","Data · Statistical analysis","Data · Campaign performance","Proven record"],
    stepPages:[["mdlz-hub/snapshot/index.html","0"],["mdlz-hub/snapshot/index.html","1"],["mdlz-hub/snapshot/index.html","2"],["mdlz-hub/snapshot/index.html","2.1"],["mdlz-hub/snapshot/index.html","2.2"],["mdlz-hub/snapshot/index.html","2.3"],["mdlz-hub/snapshot/index.html","3"]] },

  { id:"loyalty-strategy", group:"Loyalty strategy", name:"Brand strategies + Joy Club loyalty program", page:"mdlz-hub/strat/loyalty.html", w:1280, h:832,
    steps:["Loyalty program mapped according to the brand","Auto-enrolled into Joy Club","Participate & earn · what she can do","Post UGC · pick the photo","UGC · AI verification","UGC · +250 points credited","Scan a receipt · camera","Receipt · OCR & SKU check","Receipt · +240 points credited","Refer a friend · share code","Referral · friend claims","Referral · +200 points credited","Rewards & redemption","Shop, recipes & data control"],
    stepPages:[["mdlz-hub/strat/loyalty.html",0],["mdlz-hub/joyclub/index.html","0"],["mdlz-hub/joyclub/index.html","1"],["mdlz-hub/joyclub/index.html","1.1"],["mdlz-hub/joyclub/index.html","1.2"],["mdlz-hub/joyclub/index.html","1.3"],["mdlz-hub/joyclub/index.html","1.4"],["mdlz-hub/joyclub/index.html","1.5"],["mdlz-hub/joyclub/index.html","1.6"],["mdlz-hub/joyclub/index.html","1.7"],["mdlz-hub/joyclub/index.html","1.8"],["mdlz-hub/joyclub/index.html","1.9"],["mdlz-hub/joyclub/index.html","2"],["mdlz-hub/joyclub/index.html","3"]] },

  { id:"enroll-bournvita", group:"Enrollment 1 · Bournvita", name:"Approved claimant journey on the web form → Joy Club → analytics", page:"hub/bv-enrol1/index.html", w:1280, h:832,
    steps:["The journey at a glance","Form builder · questions & preview","Pack logic · age → SKU","Pixels · Meta · Google · GA4","Share form · website embed","Script pasted into bournvita.in","The ad sends her to the page","Landing page on bournvita.in","Your details · name, mobile, email","OTP · number verified","Child's age → pack allocated","What matters most right now","Where she shops → coupon","Another brand → screening","Address → courier scored live","Verification → agentic consensus","Claim confirmed → order + inventory","Shipped · tracking on the site","Gratification period","Day-7 feedback form","Coupon → Shop on Blinkit","Blinkit · coupon applied","Auto-enrolled into Joy Club","Participate & earn · what she can do","Post UGC · pick the photo","UGC · AI verification","UGC · +250 points credited","Scan a receipt · camera","Receipt · OCR & SKU check","Receipt · +240 points credited","Refer a friend · share code","Referral · friend claims","Referral · +200 points credited","Rewards & redemption","Shop, recipes & data control","Analytics · Overview","Overview · live numbers","Overview · UTM breakdown","Live Analytics · event stream","Data Visualisation · questions charted","Data Visualisation · UTM funnels","Statistical Analysis · what predicts intent","Statistical Analysis · winning combination","Campaign Performance dashboard","Saved Audiences · cohorts","All Claimants · first-party rows"],
    stepPages:[["hub/intro/index.html?c=bv",0],["hub/bv-enrol1/index.html",0],["hub/bv-enrol1/index.html",1],["hub/bv-enrol1/index.html",2],["hub/bv-enrol1/index.html",3],["hub/bv-enrol1/index.html",4],["hub/bv-enrol1/index.html",5],["hub/bv-enrol1/index.html",6],["hub/bv-enrol1/index.html",7],["hub/bv-enrol1/index.html",8],["hub/bv-enrol1/index.html",9],["hub/bv-enrol1/index.html",10],["hub/bv-enrol1/index.html",11],["hub/bv-enrol1/index.html",12],["hub/bv-enrol1/index.html",13],["hub/bv-enrol1/index.html",14],["hub/bv-enrol1/index.html",15],["hub/bv-enrol1/index.html",16],["hub/bv-enrol1/index.html",17],["hub/bv-enrol1/index.html",18],["hub/bv-enrol1/index.html",19],["hub/bv-enrol1/index.html",20],["mdlz-hub/joyclub/index.html","0"],["mdlz-hub/joyclub/index.html","1"],["mdlz-hub/joyclub/index.html","1.1"],["mdlz-hub/joyclub/index.html","1.2"],["mdlz-hub/joyclub/index.html","1.3"],["mdlz-hub/joyclub/index.html","1.4"],["mdlz-hub/joyclub/index.html","1.5"],["mdlz-hub/joyclub/index.html","1.6"],["mdlz-hub/joyclub/index.html","1.7"],["mdlz-hub/joyclub/index.html","1.8"],["mdlz-hub/joyclub/index.html","1.9"],["mdlz-hub/joyclub/index.html","2"],["mdlz-hub/joyclub/index.html","3"],["hub/analytics/index.html?c=bournvita",0],["hub/analytics/index.html?c=bournvita",1],["hub/analytics/index.html?c=bournvita",2],["hub/analytics/index.html?c=bournvita",3],["hub/analytics/index.html?c=bournvita",4],["hub/analytics/index.html?c=bournvita",5],["hub/analytics/index.html?c=bournvita",6],["hub/analytics/index.html?c=bournvita",7],["hub/analytics/index.html?c=bournvita",8],["hub/analytics/index.html?c=bournvita",9],["hub/analytics/index.html?c=bournvita",10]] },

  
  { id:"enroll-cadbury", group:"Enrollment 2 · Cadbury", name:"Receipt on WhatsApp → UPI cashback → Joy Club", page:"hub/cb-enrol2/index.html", w:1280, h:832,
    steps:["The journey at a glance","At the counter · the invisible purchase","QR on pack · scan to WhatsApp","WhatsApp invite","Receipt uploaded","UPI cashback","Auto-enrolled in Joy Club","Her Joy Club card","Analytics · Overview","Overview · live numbers","Overview · UTM breakdown","Live Analytics · receipt stream","Data Visualisation · receipts charted","Data Visualisation · UTM funnels","Statistical Analysis · what predicts a repeat receipt","Statistical Analysis · winning combination","Campaign Performance dashboard","Saved Audiences · store cohorts","All Claimants · first-party rows","Back to Mondelez"],
    stepPages:[["hub/intro/index.html?c=cb",0],["hub/cb-enrol2/index.html",0],["hub/cb-enrol2/index.html",1],["hub/cb-enrol2/index.html",2],["hub/cb-enrol2/index.html",3],["hub/cb-enrol2/index.html",4],["hub/cb-enrol2/index.html",5],["hub/cb-enrol2/index.html",6],["hub/analytics/index.html?c=cadbury",0],["hub/analytics/index.html?c=cadbury",1],["hub/analytics/index.html?c=cadbury",2],["hub/analytics/index.html?c=cadbury",3],["hub/analytics/index.html?c=cadbury",4],["hub/analytics/index.html?c=cadbury",5],["hub/analytics/index.html?c=cadbury",6],["hub/analytics/index.html?c=cadbury",7],["hub/analytics/index.html?c=cadbury",8],["hub/analytics/index.html?c=cadbury",9],["hub/analytics/index.html?c=cadbury",10],["hub/cb-enrol2/index.html",7]] },

  { id:"enroll-biscoff", group:"Enrollment 3 · Biscoff", name:"IPL TV QR → invite 10 friends → limited drop", page:"hub/bc-enrol3/index.html", w:1280, h:832,
    steps:["The journey at a glance","Scan from the sofa","WhatsApp gate · invite 10 friends","Ten friends picked","Seven of ten joined","Drop unlocked","Pincode & address in chat","Shipped & delivered","Analytics · Overview","Overview · live numbers","Overview · UTM breakdown","Live Analytics · limited-edition claims","Data Visualisation · friends added to the club","Data Visualisation · UTM funnels","Statistical Analysis · what predicts repeat purchase","Statistical Analysis · winning combination","Campaign Performance dashboard","Saved Audiences · ring cohorts","All Claimants · first-party rows","Auto-enrolled in the Loyalty Club","Back to Mondelez"],
    stepPages:[["hub/intro/index.html?c=bc",0],["hub/bc-enrol3/index.html",0],["hub/bc-enrol3/index.html",1],["hub/bc-enrol3/index.html",2],["hub/bc-enrol3/index.html",3],["hub/bc-enrol3/index.html",4],["hub/bc-enrol3/index.html",5],["hub/bc-enrol3/index.html",6],["hub/analytics/index.html?c=biscoff",0],["hub/analytics/index.html?c=biscoff",1],["hub/analytics/index.html?c=biscoff",2],["hub/analytics/index.html?c=biscoff",3],["hub/analytics/index.html?c=biscoff",4],["hub/analytics/index.html?c=biscoff",5],["hub/analytics/index.html?c=biscoff",6],["hub/analytics/index.html?c=biscoff",7],["hub/analytics/index.html?c=biscoff",8],["hub/analytics/index.html?c=biscoff",9],["hub/analytics/index.html?c=biscoff",10],["mdlz-hub/joyclub/index.html",0],["hub/bc-enrol3/index.html",7]] },

  { id:"enrich", group:"Data recall", name:"Data Enrichment · Mondelez 1PD", page:"mdlz-hub/enrich/index.html", w:1280, h:832,
    steps:["Before · two usable fields","Enrich · three records","At scale · 9.2M records","Activation-ready cohorts","Questions sent → Magic Flow builds the journey"] },
  { id:"reengage", group:"Data recall", name:"Re-engagement via Magic Flow (cohorts in)", page:"mdlz-hub/reengage/index.html", w:1280, h:832,
    steps:["Magic Flow · build","Magic Flow · published","Jan · New year","Feb · Valentine's","Mar · Holi","Apr · Recipes","May · Kids","Jun · New launch","Jul · Receipts","Aug · Rakhi","Sep · Birthday","Oct · Diwali","Nov · Reorder","Dec · Tier up","Consumer profile"] },
    { id:"promoter", group:"Appendix", name:"Promoter Sampling / Retail Activation", embed:"Mondelez Promoter Sampling Demo.html", w:1280, h:890, note:"Interactive demo · Next/Prev or arrow keys." },
  { id:"digital-sampling", group:"Appendix", name:"Digital Sampling", embed:"Mondelez Digital Sampling Demo.html", w:1280, h:890, note:"Interactive demo · Next/Prev or arrow keys." },
  { id:"creator", group:"Appendix", name:"Creator engagement · Celebrations UGC", page:"mdlz-hub/flow/creator.html", w:1280, h:832,
    steps:["Creator story","Branded WhatsApp","UGC submitted","Reward issued","Claim in Joy Club"] },
  { id:"commerce", group:"Appendix", name:"Commerce · post-order referral", page:"mdlz-hub/flow/commerce.html", w:1280, h:832,
    steps:["Post-order screen","WhatsApp consent","Refer 10 friends","10 joined","Sample shipped"] },
  { id:"analytics", group:"Appendix", name:"FreeStand Analytics (full console)", page:"mdlz-hub/analytics/index.html", w:1280, h:832,
    steps:["Campaign Performance","Statistical Analysis","Live Analytics","Data Visualisation","Overview"] },
  { id:"web-sampling", group:"Appendix", name:"Website Sampling", embed:"Mondelez Website Sampling Demo.html", w:1280, h:890, note:"Interactive demo · Next/Prev or arrow keys." },
];
