/* FreeStand admin "Design interaction" builder + modals (Assign SKUs · Pixel tracking · Share form). window.SETUP.render(step, CHAT_CONFIG) */
window.SETUP=(function(){
const esc=s=>String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;");
const MENU=["Manage Clients","Manage Campaigns","Manage Vendors","Manage SKUs","Manage Accounts","Manage Users","All Claimants","Manage Teams","Manage Audits","Manage Reports","Manage Notifications","Manage Analytics","Manage Analytics V2","Reviews","Manage Tickets","Manage Schemas","Manage PSPs","Logistics","Manage API Keys","Playbooks"];
const I={sq:'<rect x="4" y="4" width="16" height="16" rx="3"/>',users:'<circle cx="9" cy="8" r="3"/><path d="M3 20c0-3.2 2.7-5 6-5s6 1.8 6 5"/><path d="M16 11a3 3 0 1 0 0-6M17 15c2.5.4 4 1.9 4 5"/>',cal:'<rect x="3" y="4" width="18" height="17" rx="2"/><path d="M16 2v4M8 2v4M3 10h18"/>',box:'<path d="M21 8l-9-5-9 5v8l9 5 9-5z"/><path d="M3 8l9 5 9-5M12 13v8"/>',chart:'<path d="M4 20h16M7 16v-5M12 16V6M17 16v-8"/>',gear:'<circle cx="12" cy="12" r="3"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3M4.9 4.9l2.1 2.1M17 17l2.1 2.1M4.9 19.1L7 17M17 7l2.1-2.1"/>',trash:'<path d="M3 6h18M8 6V4h8v2M6 6l1 14h10l1-14"/>',copy:'<rect x="9" y="9" width="12" height="12" rx="2"/><path d="M5 15V5a2 2 0 0 1 2-2h10"/>',phone:'<rect x="7" y="2" width="10" height="20" rx="2"/><path d="M11 18h2"/>',edit:'<path d="M12 20h9M16.5 3.5a2 2 0 0 1 3 3L7 19l-4 1 1-4z"/>',back:'<path d="M19 12H5M12 19l-7-7 7-7"/>',bell:'<path d="M18 8a6 6 0 0 0-12 0c0 7-3 9-3 9h18s-3-2-3-9M13.7 21a2 2 0 0 1-3.4 0"/>',user:'<circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/>',share:'<circle cx="18" cy="5" r="3"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="19" r="3"/><path d="M8.6 13.5l6.8 4M15.4 6.5l-6.8 4"/>',ext:'<path d="M14 3h7v7M21 3l-9 9M19 14v5a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2h5"/>',lap:'<rect x="3" y="5" width="18" height="12" rx="2"/><path d="M2 19h20"/>',x:'<path d="M18 6L6 18M6 6l12 12"/>',arr:'<path d="M4 6v4a4 4 0 0 0 4 4h11M15 10l4 4-4 4"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v5M12 8h.01"/>',link:'<path d="M10 14a5 5 0 0 0 7 0l3-3a5 5 0 0 0-7-7l-1 1M14 10a5 5 0 0 0-7 0l-3 3a5 5 0 0 0 7 7l1-1"/>',code:'<path d="M16 18l6-6-6-6M8 6l-6 6 6 6"/>',chev:'<path d="M6 9l6 6 6-6"/>',home:'<path d="M3 11l9-8 9 8v10h-6v-6H9v6H3z"/>',doc:'<path d="M14 3H6a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"/><path d="M14 3v6h6M8 13h8M8 17h8"/>',clip:'<rect x="5" y="4" width="14" height="17" rx="2"/><path d="M9 2h6v4H9z"/>',chat:'<path d="M21 11.5a8.4 8.4 0 0 1-9 8.4 8.6 8.6 0 0 1-4-1L3 20l1.3-4.4A8.4 8.4 0 1 1 21 11.5z"/>',aud:'<path d="M3 13l2-6h14l2 6M3 13h18v6H3z"/><path d="M7 16h2M15 16h2"/>',card:'<rect x="2" y="5" width="20" height="14" rx="2"/><path d="M2 10h20"/>',pie:'<path d="M21 12A9 9 0 1 1 12 3v9z"/><path d="M21 8a9 9 0 0 0-6-5v6h6z"/>',star:'<path d="M12 2l3 6.6 7 .8-5.2 4.8 1.4 7L12 17.7 5.8 21.2l1.4-7L2 9.4l7-.8z"/>',check:'<rect x="3" y="3" width="18" height="18" rx="3"/><path d="M8 12l3 3 6-7"/>',ucheck:'<circle cx="9" cy="8" r="4"/><path d="M2 21a7 7 0 0 1 14 0M16 11l2 2 4-4"/>',help:'<circle cx="12" cy="12" r="9"/><path d="M9.5 9.5a2.5 2.5 0 1 1 3.5 2.3c-.7.4-1 1-1 1.7M12 17h.01"/>',head:'<path d="M4 14v-2a8 8 0 0 1 16 0v2"/><rect x="3" y="13" width="4" height="6" rx="1.5"/><rect x="17" y="13" width="4" height="6" rx="1.5"/>'};
const ic=(n,s,c)=>'<svg width="'+(s||14)+'" height="'+(s||14)+'" viewBox="0 0 24 24" fill="none" stroke="'+(c||"currentColor")+'" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">'+I[n]+'</svg>';
const MI=["users","cal","box","box","users","users","users","users","sq","chart","bell","chart","chart","sq","sq","sq","sq","box","sq","sq"];
const UU=["d6c8d1e8-5d6c-418e-b67c-602b65222267","de6e1959-bca7-4c02-8124-ac4327847e53","d8cd8501-4e7c-4cf7-af33-6e1a574372cd","b00c0a39-c54a-4cbf-8cc5-2a1e9f0c7d41"];
const NAV=[["home","Home"],["cal","Campaigns","20"],["doc","Planner"],["CATALOGUE"],["clip","SKUs"],["box","Inventory"],["ENGAGE"],["chat","Reengage"],["aud","Audience"],["card","My Coupons"],["INSIGHTS"],["pie","Analytics"],["chart","Reports"],["star","Reviews"],["check","Audits"],["OPERATIONS"],["users","Promoters"],["users","Retailers"],["ucheck","Customer Portal"],["help","Query resolution"]];
function side(){ return '<aside class="fa-side"><div class="fa-logo"><img src="../shared/assets/fs-logo.png" alt="FreeStand"><span>«</span></div><nav>'+NAV.map(n=>n.length===1?'<div class="fa-sec">'+n[0]+'</div>':'<div class="fa-mi'+(n[1]==="Campaigns"?" on":"")+'">'+ic(n[0],16)+n[1]+(n[2]?'<b>'+n[2]+'</b>':"")+'</div>').join("")+'</nav><div class="fa-foot"><div class="fa-mi">'+ic("user",16)+'Profile</div><div class="fa-mi">'+ic("head",16)+'Help</div></div></aside>'; }
function formPrev(s){ return '<div class="fa-phone"><div class="fa-notch"></div><div class="fa-scr">'+(s.hero?'<div class="fa-hero" style="background:'+s.hero+'"><b>'+esc(s.heroT||"")+'</b></div>':"")+'<div class="fa-fh">'+esc(s.formTitle||"Get your free sample now!")+'</div>'+(s.fields||["Name","Email ID","Mobile number"]).map(f=>'<div class="fa-f"><b>'+f+'</b><span>Enter your '+f.toLowerCase()+'</span><i></i></div>').join("")+'<div class="fa-tc">☑ By proceeding, you confirm that you are above 18 years of age and consent to the processing of your personal data in accordance with the notice below.</div><div class="fa-pb">'+esc(s.formCta||"Continue")+'</div><div class="fa-pw">powered by <img src="../shared/assets/fs-logo.png" alt=""></div></div></div>'; }
function builder(s,C){
 const pages=s.pages.map((p,i)=>'<div class="fa-page"><span class="fa-drag">⋮⋮</span><div class="fa-ph"><b>Page '+((s.pageNos&&s.pageNos[i])||(i+1))+'</b><span class="fa-uuid">'+UU[i%4]+' '+ic("copy",12)+'</span><span class="fa-gear">'+ic("gear",15)+'</span></div>'+p.map((q,j)=>'<div class="fa-q"><span class="fa-drag">⋮⋮</span><span class="fa-l">'+"ABC"[j]+'</span><div><div class="t">'+esc(q[0])+'</div><div class="s">'+esc(q[1])+'</div></div><span class="fa-tr">'+ic("trash",14)+'</span></div>').join("")+'<div class="fa-add">+ Add question</div><span class="fa-tr pg">'+ic("trash",14)+'</span></div>').join("");
 const fixed=(s.fixed||[["Signup","Always Enabled"]]).map(f=>'<div class="fa-card row">'+ic("phone",15)+'<b>'+f[0]+'</b><span class="fa-ok">'+f[1]+'</span><span class="fa-gear">'+ic("gear",15)+'</span></div>').join("");
 const after=(s.after||["Claim Success 🎉"]).map(a=>'<div class="fa-card row"><b>'+a+'</b></div>').join("");
 const prev=s.preview==="line"?'<div class="fa-ln">'+LINE.phone(C.brand,LINE.bot(s.pages[0][0][0],s.previewOpts||["Yes","No"]),{x:0,y:0,date:"Today"})+'</div>':formPrev(s);
 const spot=!!(s.modal&&s.spot);
 return '<div class="fa'+(s.modal?(spot?" spot":" dim"):"")+'">'+side()+'<main class="fa-main"><div class="fa-top"><div class="fa-tt">Design interaction</div><div class="fa-hi">Hi Apurva Sharma, Good afternoon! 🌤<span class="fa-bell">'+ic("bell",17)+'<i>99+</i></span>'+ic("user",17)+'</div></div>'
 +'<div class="fa-body"><div class="fa-hd"><span class="fa-back">'+ic("back",16,"#fff")+'</span><h2>'+esc(s.title)+'</h2>'+ic("edit",15,"#6B7280")+'<div class="fa-acts"><span>Create Bot Fields</span><span>Create FSChat Variables</span><span class="o">Manage SKUs</span><span class="sq">'+ic("gear",15,"#fff")+'</span><span>Publish</span><span class="p">Share '+ic("share",13,"#fff")+'</span><span class="o">Preview '+ic("ext",13)+'</span></div></div>'
 +'<div class="fa-cols"><div class="fa-left">'+fixed+pages+'<div class="fa-addp">+ Add page</div>'+after+'</div><div class="fa-right'+(spot?" hi":"")+'">'+(spot?'<span class="fa-hl">'+esc(s.spot)+'</span>':"")+'<span class="fa-reset">Reset</span><div class="fa-prev">'+prev+'</div><div class="fa-dev"><span class="on">'+ic("phone",14,"#fff")+'</span><span>'+ic("lap",14)+'</span></div></div></div></div></main>'
 +(s.modal?'<div class="fa-dim"></div>'+(spot?'<svg class="fa-arw" viewBox="0 0 124 116"><path d="M4 18 C62 18 58 72 106 72" fill="none" stroke="#FA6600" stroke-width="2.4" stroke-dasharray="280" stroke-dashoffset="280" style="animation:ebDraw 1s .4s forwards"/><path d="M98 65l9 7-9 7" fill="none" stroke="#FA6600" stroke-width="2.4" style="animation:faIn .3s 1.3s both"/></svg>':"")+'<div class="fa-ov"><div class="fa-md '+s.modal+'">'+MOD[s.modal](s,C)+'</div></div>':"")+callout(s)+'</div>';
}
const MOD={
 skus:(s)=>{ const m=s.sku; return '<div class="fa-mh"><div><b>Assign SKUs</b><span>Conditionally assign SKUs to claimants based on their responses</span></div>'+ic("x",18)+'</div>'
  +m.rules.map((r,i)=>'<div class="fa-logic" style="animation-delay:'+(i*.12)+'s"><div class="fa-if">'+ic("arr",14)+'<span>If answer to</span><div class="sel">'+esc(m.q)+' '+ic("chev",12)+'</div><div class="sel">is '+ic("chev",12)+'</div><div class="sel v">'+esc(r.ans)+'</div>'+ic("trash",14,"#6B7280")+'<span class="and">AND</span></div><div class="fa-then"><span>then assign SKU(s)</span><div class="chips">'+m.skus.map((k,j)=>'<div class="fa-sku'+(j===r.pick?" on":"")+'">'+esc(k)+'<i>'+(j===r.pick?"✓":"")+'</i></div>').join("")+'</div></div></div>').join("")
  +'<div class="fa-addl">+ Add logic</div><div class="fa-info">'+ic("info",16,"#1D4ED8")+'<div>• If <b>none</b> of the conditions are met, <b>All SKU(s)</b> in the campaign will be assigned<br>• If <b>multiple</b> conditions are met, the <b>first</b> logic will be applied</div></div><div class="fa-mf"><span class="o" data-go="1">Close</span><span class="p" data-go="1">Save</span></div>'; },
 pixels:(s)=>{ const p=s.pixel; return '<div class="fa-mh"><div><b>Interaction Settings</b><span>Update settings for this interaction. Changes will be reflected immediately.</span></div>'+ic("x",18)+'</div>'
  +'<div class="fa-tabs">'+["Appearance","TnC","Validity & Limits","Referrers","Pixel Tracking"].map(t=>'<span'+(t==="Pixel Tracking"?' class="on"':"")+'>'+t+'</span>').join("")+'</div>'
  +'<div class="fa-tog"><i></i>Enable Pixel Tracking</div><div class="fa-seg"><span class="on">Marketing Pixels</span><span>Events</span></div>'
  +'<div class="fa-px"><div class="fa-pxh"><div><b>Marketing Pixel 1</b><span>'+esc(p.platform)+'</span></div>'+ic("trash",15,"#6B7280")+'</div><label>Platform</label><div class="fa-in">'+esc(p.platform)+ic("chev",12)+'</div><label>Name (for your reference)</label><div class="fa-in">'+esc(p.name)+'</div><label>'+esc(p.platform)+' ID</label><div class="fa-in">'+esc(p.id)+'</div><small>Found in your '+esc(p.mgr||"Facebook Events Manager")+'. Looks like: 1234567890123456</small><label>Initialization Code</label><pre class="fa-code">'+esc(p.code||"!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?\nn.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;\nn.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;\nt.src=v;s=b.getElementsByTagName(e)[0];")+'</pre></div>'
  +(s.more||[]).map(m=>'<div class="fa-px mini"><b>'+esc(m[0])+'</b><span>'+esc(m[1])+'</span><span class="fa-ok">Enabled</span></div>').join("")
  +'<div class="fa-addl">+ Add Marketing Pixel</div><div class="fa-mf"><span class="p" data-go="1">Save</span><span class="o" data-go="1">Close</span></div>'; },
 live:(s,C)=>{ const l=s.live; const rows=[["LINE Official Account",l.account+" · verified · "+l.friends+" friends","Connected"],["Messaging API webhook","https://api.freestand.jp/line/webhook/"+(C.campaignId||"").toLowerCase(),"Verified"],["Rich menu & greeting message","Free sample campaign · Feeding guide · Official website","Published"],["Add-friend link with UTM",l.utm,"Ready"]];
  return '<div class="fa-mh"><div><b>Take live on LINE</b><span>Publish this interaction to the brand\'s LINE Official Account · no code on the brand side.</span></div>'+ic("x",18)+'</div>'
  +rows.map((r,i)=>'<div class="fa-px mini" style="animation:faIn .35s '+(i*.12)+'s both"><div style="flex:1;min-width:0"><b>'+esc(r[0])+'</b><br><span style="word-break:break-all">'+esc(r[1])+'</span></div><span class="fa-ok">'+r[2]+'</span></div>').join("")
  +'<div class="fa-info">'+ic("info",16,"#1D4ED8")+'<div>Customers who tap the ad are taken to LINE, add the account as a friend and the conversation starts from <b>Page 1</b>. Every reply is stored on the customer profile.</div></div><div class="fa-mf"><span class="o" data-go="1">Close</span><span class="p" data-go="1">Publish & go live</span></div>'; },
 share:(s)=>{ const u=s.utm; const F=[["Source","source","Where the traffic originates"],["Medium","medium","The marketing channel or format"],["Campaign","campaign","The campaign or promotion name"],["Content","content","The creative, placement, or message"],["Term","term","The keyword or targeting term"],["Platform","platform","The platform or device context"],["Audience","audience","The audience segment being targeted"],["Variant","variant","The experiment or link variant"]];
  return '<div class="fa-mh sh"><span class="fa-shi">'+ic("share",18,"#052762")+'</span><div><b>Share form</b><span>Build a trackable campaign link, protect access, or embed the form on your website.</span></div>'+ic("x",18)+'</div>'
  +'<div class="fa-utm">'+F.map(f=>'<div class="fa-uf"><div class="l">'+f[0]+'<code>utm_'+f[1]+'</code></div><div class="fa-in'+(u[f[1]]?" v":"")+'">'+esc(u[f[1]]||"e.g. "+f[1])+'</div><small>'+f[2]+'</small></div>').join("")+'</div>'
  +'<div class="fa-ready"><b>Ready to share</b><span>Tracking values are applied live to every link and embed below.</span></div><div class="fa-seg wide"><span'+(s.mode==="embed"?"":' class="on"')+'>'+ic("link",13)+' Share link</span><span'+(s.mode==="embed"?' class="on"':"")+'>'+ic("code",13)+' Embed code</span></div>'
  +'<div class="fa-emb'+(s.spot?" hi":"")+'"><div class="h"><b>'+(s.mode==="embed"?"Website embed":"Campaign link")+'</b><span class="p">'+ic("copy",13,"#fff")+' Copy '+(s.mode==="embed"?"code":"link")+'</span></div><pre>'+esc(s.code)+'</pre></div>'
  +'<div class="fa-mf sp"><span class="ok">✓ Values are URL-encoded automatically.</span><span class="o" data-go="1">Close</span></div>'; }
};
function callout(s){ if(!s.call)return ""; const c=s.call;
 return '<div class="fa-call"><span class="k">'+esc(c.k||"WHAT’S HAPPENING")+'</span><b>'+esc(c.t)+'</b><p>'+c.s+'</p>'
 +(c.pts?'<ul>'+c.pts.map(p=>'<li><i>✓</i><span>'+p+'</span></li>').join("")+'</ul>':"")
 +'<span class="fa-cbtn" data-go="1">'+esc(c.cta||"Got it · next")+' →</span></div>'; }
function intro(s,C){
 return '<div class="fa-intro"><div class="in-l"><div class="k">'+esc(s.kicker||"WEBSITE SAMPLING")+'</div><h1>'+s.title+'</h1><p>'+s.sub+'</p>'
 +'<div class="in-meta">'+(s.meta||[]).map(m=>'<div><small>'+esc(m[0])+'</small><b>'+esc(m[1])+'</b></div>').join("")+'</div>'
 +'<img class="in-fs" src="../shared/assets/fs-logo.png" alt="FreeStand">'
 +(s.logo?'<img class="in-br" src="'+s.logo+'" alt="">':"")+'</div>'
 +'<div class="in-r">'+(s.phases||[]).map((p,i)=>'<div class="in-ph" style="animation-delay:'+(i*0.14)+'s"><span class="n">'+(i+1)+'</span><div><b>'+esc(p[0])+'</b><span>'+p[1]+'</span>'+(p[2]?'<div class="tg">'+p[2].map(t=>'<i>'+esc(t)+'</i>').join("")+'</div>':"")+'</div></div>').join("")
 +'<div class="in-go" data-go="1">'+esc(s.cta||"Start with the campaign builder")+' →</div></div></div>';
}
function integrate(s,C){
 const W=C.web||{}, F=s.fields||["Full name","Mobile number","Email ID"];
 const code='<span class="c">&lt;!-- paste once, anywhere on the page --&gt;</span>\n<span class="t">&lt;script</span> <span class="a">defer src</span>=<span class="v">"'+(W.script||"trysample.freestand.jp")+'/api/script.js"</span><span class="t">&gt;&lt;/script&gt;</span>\n<span class="t">&lt;iframe</span>\n  <span class="a">id</span>=<span class="v">"freestand-integration"</span>\n  <span class="a">src</span>=<span class="v">"…/interactions/c41f8b7d"</span>\n  <span class="a">width</span>=<span class="v">"100%"</span> <span class="a">height</span>=<span class="v">"600"</span><span class="t">&gt;</span>\n<span class="t">&lt;/iframe&gt;</span>';
 const lap='<div class="fa-lap"><div class="scr"><div class="in">'
  +'<div class="eb-side">'+[0,1,2,3,4,5,6,7].map(()=>'<u></u>').join("")+'</div>'
  +'<div class="eb-main"><div class="eb-top">Design interaction</div><div class="eb-bar"></div><div class="eb-cards">'+[0,1,2,3,4,5].map(()=>'<div></div>').join("")+'</div></div>'
  +'<div class="eb-md"><b>Share form</b><div class="s">Trackable link, access control or website embed.</div>'
   +'<div class="lbl">Embed this form in your website</div><div class="row hi"><code>&lt;iframe src="'+(W.script||"trysample.freestand.jp")+'/interactions/c41f…"&gt;</code><i>⧉</i></div>'
   +'<span class="cls">Close</span></div>'
  +'</div><div class="base"></div></div></div>';
 const ph='<div class="eb-ph"><span class="eb-lbl">'+esc(W.site||"nestle.jp")+'</span><div class="sc">'
  +'<div class="eb-brand">'+(W.logo?'<img src="'+W.logo+'" alt="">':'<b>'+esc(W.name||C.brand)+'</b>')+'</div>'
  +'<div class="eb-slot"><pre class="eb-code">'+code+'</pre>'
   +'<div class="eb-form"><div class="hero" style="background:'+(s.hero||"#0A49B7")+';color:#0b2340">'+esc(s.heroT||"")+'</div>'
   +'<div class="ttl">'+esc(s.formTitle||"Get your free sample")+'</div>'
   +F.map(f=>'<div class="f"><b>'+esc(f)+'</b><i></i></div>').join("")
   +'<div class="btn">'+esc(s.formCta||"Continue")+'</div></div>'
   +'<div class="eb-flash"></div></div>'
  +'<div class="eb-skel"><u></u><u style="width:60%"></u><div class="r"><u></u><u></u></div><u style="width:80%"></u><div class="r"><u></u><u></u><u></u></div></div>'
  +'<div class="eb-pw">Powered by<img src="../shared/assets/fs-logo.png" alt="FreeStand"></div>'
  +'</div></div>';
 return '<div class="fa-int">'+(s.head?'<div style="font-size:8.5px;font-weight:800;letter-spacing:1.6px;color:#9AA3B2;text-transform:uppercase;margin-bottom:6px">'+esc(Array.isArray(s.head)?s.head[1]:s.head)+'</div>':"")+'<h1>'+esc(s.title2||"The form is integrated into your website")+'</h1>'
  +'<div class="isub">'+esc(s.sub||"One paste. No developer, no release cycle.")+'</div>'
  +lap
  +'<svg class="arw" viewBox="0 0 186 150"><path d="M4 26 C92 26 96 104 178 104"/><path d="M168 96l11 8-11 8" style="stroke-dasharray:none;stroke-dashoffset:0;animation:faIn .3s 1.2s both"/></svg>'
  +ph
  +'<div class="ichips">'+(s.chips||["Script → live form","Nestlé keeps the page","FreeStand keeps the logic"]).map(c=>'<i>'+esc(c)+'</i>').join("")+'</div>'
  +'<div class="igo" data-go="1">'+esc(s.cta||"See how she arrives")+' →</div></div>';
}
function render(s,C){ return s.kind==="intro"?intro(s,C):s.kind==="integrate"?integrate(s,C):builder(s,C); }
return {render:render};
})();
